services:
  keycloak-postgres:
      image: postgres:15.4-bullseye
      container_name: keycloak-postgres
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
      networks:
        - keycloak      
      restart: unless-stopped

  keycloak:
      container_name: keycloak
      command: start-dev --log-level="INFO"
      image: keycloak-docker:latest
      build:
        context: ./keycloak/build
        dockerfile: Dockerfile
      environment:
        KEYCLOAK_ADMIN: user
        KEYCLOAK_ADMIN_PASSWORD: password
        KC_DB_URL: jdbc:postgresql://keycloak-postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: password
        KC_DB: postgres
        KC_HOSTNAME: localhost.domain
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. 
        # It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
      ports:
        - 0.0.0.0:80:8080
        - 0.0.0.0:443:8443
      depends_on:
        - keycloak-postgres
      networks:
        - keycloak
      volumes:
        - ./keycloak/volumes/scripts/entrypoint.sh:/app/entrypoint.sh
        - ./keycloak/volumes/data/:/mnt/keycloak/
      restart: unless-stopped        

networks:
  keycloak:
    name: keycloak

